spring.application.name=spring-boot-rest

spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=1107
spring.datasource.driver-class-name=org.postgresql.Driver



server.servlet.session.cookie.same-site=strict

spring.jpa.hibernate.ddl-auto=update
spring.jpa.sql-show=true